/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;
import java.io.IOException;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author HP VICTUS
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);  
        setAlwaysOnTop(false);
        scaleImage1();
        scaleImage2();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlebar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        app1 = new javax.swing.JLabel();
        app2 = new javax.swing.JLabel();
        app3 = new javax.swing.JLabel();
        app4 = new javax.swing.JLabel();
        app5 = new javax.swing.JLabel();
        office = new javax.swing.JPanel();
        app6 = new javax.swing.JLabel();
        app7 = new javax.swing.JLabel();
        app8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));

        titlebar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        title.setText("Laboratorium STMIK Kharisma Makassar");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/close_nohover.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout titlebarLayout = new javax.swing.GroupLayout(titlebar);
        titlebar.setLayout(titlebarLayout);
        titlebarLayout.setHorizontalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );
        titlebarLayout.setVerticalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.setMinimumSize(new java.awt.Dimension(0, 0));

        app1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        app1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/Apache_NetBeans_Logo.png"))); // NOI18N
        app1.setToolTipText("");
        app1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app1.setMaximumSize(new java.awt.Dimension(32, 32));
        app1.setMinimumSize(new java.awt.Dimension(32, 32));
        app1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app1MouseClicked(evt);
            }
        });

        app2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/Google_Chrome_Logo.png"))); // NOI18N
        app2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app2MouseClicked(evt);
            }
        });

        app3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/vscode.png"))); // NOI18N
        app3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app3MouseClicked(evt);
            }
        });

        app4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app4.setPreferredSize(new java.awt.Dimension(254, 256));
        app4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app4MouseClicked(evt);
            }
        });

        app5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app5MouseClicked(evt);
            }
        });

        office.setBorder(javax.swing.BorderFactory.createTitledBorder("Office"));

        app6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/Excel_96x96.png"))); // NOI18N
        app6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app6MouseClicked(evt);
            }
        });

        app7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/Word_96x96.png"))); // NOI18N
        app7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app7MouseClicked(evt);
            }
        });

        app8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectfinal/assets/PowerPoint_96x96.png"))); // NOI18N
        app8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout officeLayout = new javax.swing.GroupLayout(office);
        office.setLayout(officeLayout);
        officeLayout.setHorizontalGroup(
            officeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(officeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(app6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(app7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(app8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        officeLayout.setVerticalGroup(
            officeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(app7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(app8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(app1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(app3)
                .addGap(18, 18, 18)
                .addComponent(app4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(app5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(app2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(app1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(app3)
                            .addComponent(app4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(app2)
                    .addComponent(app5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static ImageIcon ii;
    public void scaleImage1(){
        ImageIcon icon = new ImageIcon("C:\\Users\\HP VICTUS\\Documents\\NetBeansProjects\\ProjectFinal\\src\\projectfinal\\assets\\xampp.254x256.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(app4.getWidth(),app4.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        app4.setIcon(scaledIcon);
    }
    public void scaleImage2(){
        ImageIcon icon = new ImageIcon("C:\\Users\\HP VICTUS\\Documents\\NetBeansProjects\\ProjectFinal\\src\\projectfinal\\assets\\icons8-file-explorer-48.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(app5.getWidth(),app5.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        app5.setIcon(scaledIcon);
    }
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("assets/close_hover.png"));
        exit.setIcon(ii);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("assets/close_nohover.png"));
        exit.setIcon(ii);
    }//GEN-LAST:event_exitMouseExited

    private void app1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app1MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Program Files\\NetBeans-19\\netbeans\\bin\\netbeans64.exe\"");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app1MouseClicked

    private void app2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app2MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Users\\HP VICTUS\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app2MouseClicked

    private void app3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app3MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Users\\HP VICTUS\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app3MouseClicked

    private void app4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app4MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("cmd /c \"C:\\xampp\\xampp-control.exe\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app4MouseClicked

    private void app5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app5MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("explorer.exe");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app5MouseClicked

    private void app6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app6MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app6MouseClicked

    private void app7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app7MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app7MouseClicked

    private void app8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app8MouseClicked
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("\"C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE\"");
        }catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_app8MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app1;
    private javax.swing.JLabel app2;
    private javax.swing.JLabel app3;
    private javax.swing.JLabel app4;
    private javax.swing.JLabel app5;
    private javax.swing.JLabel app6;
    private javax.swing.JLabel app7;
    private javax.swing.JLabel app8;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel main;
    private javax.swing.JPanel office;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlebar;
    // End of variables declaration//GEN-END:variables
}
